GET http://localhost:3000/api/usuarios

###

GET http://localhost:3000/api/usuarios/2

###

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "username": "Ale3",
    "email": "prueba3@uv.mx",
    "password": "patito3",
    "nombre": "Un nuevo usuario pato3",
    "rol": "Administrador"
}

###

PUT http://localhost:3000/api/usuarios/3
Content-Type: application/json

{
    "id": 3,
    "nombre": "Usuario pato editado",
    "rol": "Usuario"
}

###

DELETE http://localhost:3000/api/usuarios/3